name: デプロイワークフロー

on:
  push:
    branches:
      - main  # メインブランチへのプッシュ時に実行
  workflow_dispatch:  # 手動実行も可能

env:
  AWS_REGION: ap-northeast-1  # 東京リージョン
  STACK_NAME: CdkStack

jobs:
  build-ui:
    name: UIのビルド
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: Node.jsのセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './ui/package-lock.json'

      - name: UI依存関係のインストール
        run: |
          cd ui
          npm ci

      - name: UIのビルド
        run: |
          cd ui
          npm run build

      - name: UIビルド成果物のアップロード
        uses: actions/upload-artifact@v4
        with:
          name: ui-build
          path: get-satellite-image/ui/dist
          retention-days: 1

  deploy-lambda-postgis:
    name: PostGIS拡張用Lambdaのデプロイ
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: Pythonのセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: 依存関係のインストール
        run: |
          cd lambda/postgis-extension
          pip install -r requirements.txt -t .

      - name: Lambdaデプロイパッケージの作成
        run: |
          cd lambda/postgis-extension
          zip -r ../postgis-extension.zip .

      - name: Lambdaパッケージのアップロード
        uses: actions/upload-artifact@v4
        with:
          name: postgis-extension-lambda
          path: lambda/postgis-extension.zip
          retention-days: 1

  deploy-cdk:
    name: CDKデプロイ
    runs-on: ubuntu-latest
    needs: [build-ui, deploy-lambda-postgis]
    permissions:
      id-token: write  # OIDCトークン取得のために必要
      contents: read

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: UIビルド成果物のダウンロード
        uses: actions/download-artifact@v4
        with:
          name: ui-build
          path: get-satellite-image/ui/dist

      - name: PostGIS Lambdaパッケージのダウンロード
        uses: actions/download-artifact@v4
        with:
          name: postgis-extension-lambda
          path: get-satellite-image/lambda
          
      - name: Lambdaパッケージの展開と確認
        run: |
          # postgis-extensionディレクトリが存在するか確認し、なければ作成
          echo "Lambdaパッケージの展開を開始します"
          LAMBDA_DIR="lambda/postgis-extension"
          
          if [ ! -d "$LAMBDA_DIR" ]; then
            echo "$LAMBDA_DIR ディレクトリが存在しないため作成します"
            mkdir -p "$LAMBDA_DIR"
          fi
          
          # zipファイルが存在する場合は展開
          if [ -f lambda/postgis-extension.zip ]; then
            echo "zipファイルを展開します"
            unzip -o lambda/postgis-extension.zip -d "$LAMBDA_DIR"
          else
            echo "警告: postgis-extension.zipが見つかりません"
            # 代わりにリポジトリのファイルをコピー
            echo "リポジトリのファイルをコピーします"
            cp -r lambda/postgis-extension/* "$LAMBDA_DIR/"
          fi
          
          # ディレクトリ内容の確認
          echo "Lambdaディレクトリの内容:"
          ls -la lambda/
          echo "Lambdaパッケージの内容:"
          ls -la "$LAMBDA_DIR" || echo "ディレクトリは空か存在しません"

      - name: Lambda関数コードの準備
        run: |
          cd get-satellite-image/cdk
          
          # postgis-extensionディレクトリが存在するか確認
          if [ ! -d "postgis-extension" ]; then
            mkdir -p postgis-extension
          fi
          
          # リポジトリからLambda関数のコードをコピー
          echo "Lambda関数のコードをコピーします"
          cp -r ../../lambda/postgis-extension/* postgis-extension/
          
          # ファイルの存在確認
          echo "コピーしたファイルの確認:"
          ls -la postgis-extension/

      - name: Node.jsのセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './cdk/package-lock.json'

      - name: AWS認証の設定
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # GitHubActionsからAWSリソースにアクセスするためのロール
          aws-region: ${{ env.AWS_REGION }}

      - name: CDK依存関係のインストール
        run: |
          cd cdk
          npm ci

      - name: S3バケットの作成
        run: |
          # テンプレート保存用のS3バケットを作成
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          # バケット名は小文字で、ハイフンのみ使用可能
          TEMPLATE_BUCKET="cf-templates-$(echo ${{ env.STACK_NAME }} | tr '[:upper:]' '[:lower:]')-${{ env.AWS_REGION }}-${ACCOUNT_ID}"
          
          # バケットが存在するか確認
          if ! aws s3 ls s3://${TEMPLATE_BUCKET} 2>/dev/null; then
            echo "Creating S3 bucket: ${TEMPLATE_BUCKET}"
            aws s3 mb s3://${TEMPLATE_BUCKET} --region ${{ env.AWS_REGION }}
          else
            echo "S3 bucket already exists: ${TEMPLATE_BUCKET}"
          fi
          
          # バケット名を環境変数に設定
          echo "TEMPLATE_BUCKET=${TEMPLATE_BUCKET}" >> $GITHUB_ENV
      
      - name: CDKスタックの合成とデプロイ
        id: deploy
        continue-on-error: true
        run: |
          cd cdk
          
          # Lambda関数のコードをアセットとして使用するように設定を確認
          echo "CDKスタックの設定を確認します"
          
          # CDKの設定ファイルを作成してブートストラップチェックをスキップ
          mkdir -p ~/.cdk
          echo '{"version":"1.0.0","bootstrapStackVersionSsmParameter":"","requireApproval":"never"}' > ~/.cdk/config.json
          
          # CloudFormationテンプレートを生成
          npx cdk synth ${{ env.STACK_NAME }} --no-version-reporting > template.yaml
          
          # 通知メッセージを除外
          sed -i '/NOTICES/,/cdk acknowledge/d' template.yaml
          
          # CloudFormationスタックをデプロイ
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name ${{ env.STACK_NAME }} \
            --s3-bucket ${TEMPLATE_BUCKET} \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
            --no-fail-on-empty-changeset
      
      - name: スタックイベントの取得と表示
        if: steps.deploy.outcome == 'failure'
        run: |
          echo "スタックデプロイが失敗しました。イベントを確認します。"
          aws cloudformation describe-stack-events --stack-name ${{ env.STACK_NAME }} --query "StackEvents[?ResourceStatus=='CREATE_FAILED' || ResourceStatus=='UPDATE_FAILED'].{Status:ResourceStatus,Reason:ResourceStatusReason,LogicalId:LogicalResourceId,Timestamp:Timestamp}" --output table

      - name: デプロイ結果の取得
        id: outputs
        run: |
          API_ENDPOINT=$(aws cloudformation describe-stacks --stack-name ${{ env.STACK_NAME }} --query "Stacks[0].Outputs[?OutputKey=='ApiEndpoint'].OutputValue" --output text)
          UI_ENDPOINT=$(aws cloudformation describe-stacks --stack-name ${{ env.STACK_NAME }} --query "Stacks[0].Outputs[?OutputKey=='UiEndpoint'].OutputValue" --output text)
          DB_ENDPOINT=$(aws cloudformation describe-stacks --stack-name ${{ env.STACK_NAME }} --query "Stacks[0].Outputs[?OutputKey=='DatabaseEndpoint'].OutputValue" --output text)
          echo "API_ENDPOINT=${API_ENDPOINT}" >> $GITHUB_ENV
          echo "UI_ENDPOINT=${UI_ENDPOINT}" >> $GITHUB_ENV
          echo "DB_ENDPOINT=${DB_ENDPOINT}" >> $GITHUB_ENV
          
          # S3バケットの物理IDを取得
          echo "S3バケットの物理IDを取得します"
          # CloudFormationスタックのリソース一覧を取得
          aws cloudformation list-stack-resources --stack-name ${{ env.STACK_NAME }} > stack-resources.json
          # SatelliteImageUiBucketの物理IDを抽出
          S3_BUCKET=$(cat stack-resources.json | jq -r '.StackResourceSummaries[] | select(.LogicalResourceId=="SatelliteImageUiBucket") | .PhysicalResourceId')
          echo "S3バケット名: ${S3_BUCKET}"
          echo "S3_BUCKET=${S3_BUCKET}" >> $GITHUB_ENV
      
      - name: UIファイルをS3にアップロード
        run: |
          echo "UIファイルをS3バケットにアップロードします: ${S3_BUCKET}"
          
          # S3バケット名が取得できているか確認
          if [ -z "${S3_BUCKET}" ] || [ "${S3_BUCKET}" = "None" ]; then
            echo "S3バケット名が取得できていません。CloudFormationスタックから手動で取得します。"
            # スタックリソースを再取得
            aws cloudformation list-stack-resources --stack-name ${{ env.STACK_NAME }} > stack-resources.json
            S3_BUCKET=$(cat stack-resources.json | jq -r '.StackResourceSummaries[] | select(.LogicalResourceId=="SatelliteImageUiBucket") | .PhysicalResourceId')
            echo "再取得したS3バケット名: ${S3_BUCKET}"
            
            # まだ取得できない場合はエラー
            if [ -z "${S3_BUCKET}" ] || [ "${S3_BUCKET}" = "None" ]; then
              echo "ERROR: S3バケット名を取得できませんでした。UIファイルのアップロードをスキップします。"
              exit 0
            fi
          fi
          
          # UIファイルをS3にアップロード
          aws s3 sync ui/dist s3://${S3_BUCKET} --delete
          
          # CloudFrontキャッシュを無効化
          DISTRIBUTION_ID=$(aws cloudformation list-stack-resources --stack-name ${{ env.STACK_NAME }} | jq -r '.StackResourceSummaries[] | select(.LogicalResourceId=="SatelliteImageDistribution") | .PhysicalResourceId')
          if [ ! -z "${DISTRIBUTION_ID}" ]; then
            echo "CloudFrontキャッシュを無効化します: ${DISTRIBUTION_ID}"
            aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths "/*"
          fi

      - name: デプロイ結果の出力
        run: |
          echo "デプロイが完了しました！"
          echo "APIエンドポイント: ${API_ENDPOINT}"
          echo "UIエンドポイント: ${UI_ENDPOINT}"
          echo "データベースエンドポイント: ${DB_ENDPOINT}"
